# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDo-v2' do
  use_frameworks!

  # Pods for ToDo-v2
  pod 'RealmSwift'
  pod 'SwipeCellKit'

  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
end
